### ISSUE TITLE
ImportError: cannot import name 'ExpiredSignatureError'

### ISSUE THREAD

**Issue by pingisheng** [vimalloc/flask-jwt-extended#204] opened 2018-11-07 06:22 UTC
I got a  traceback
   from flask_jwt_extended import jwt_required
  File "D:\Program Files\Python\Python36\lib\site-packages\flask_jwt_extended\__init__.py", line 1, in <module>
    from .jwt_manager import JWTManager
  File "D:\Program Files\Python\Python36\lib\site-packages\flask_jwt_extended\jwt_manager.py", line 3, in <module>
    from jwt import ExpiredSignatureError, InvalidTokenError
ImportError: cannot import name 'ExpiredSignatureError'

**Comment by pingisheng** [comment] 2018-11-07 07:15
I solved by installing PyJWT==1.6.1

**Comment by vimalloc** [comment] 2018-11-07 15:51
Glad you got that figured out. I'm going to close this issue, feel free to re-open it or make a new issue if you are still having problems :+1:

**Closed by vimalloc** 2018-11-07 15:51 UTC

**Comment by sraghavan-eqix** [comment] 2019-03-14 02:37
Still getting this error as shown below
    from flask_jwt_extended import jwt_required, get_jwt_identity, get_raw_jwt
  File "/usr/local/lib/python3.7/site-packages/Flask_JWT_Extended-3.18.0-py3.7.egg/flask_jwt_extended/__init__.py", line 1, in <module>
    from .jwt_manager import JWTManager
  File "/usr/local/lib/python3.7/site-packages/Flask_JWT_Extended-3.18.0-py3.7.egg/flask_jwt_extended/jwt_manager.py", line 4, in <module>
    from jwt import ExpiredSignatureError, InvalidTokenError, InvalidAudienceError
ImportError: cannot import name 'ExpiredSignatureError' from 'jwt' (/usr/local/lib/python3.7/site-packages/jwt-0.6.1-py3.7.egg/jwt/__init__.py)

**Comment by vimalloc** [comment] 2019-03-14 02:57
> jwt-0.6.1-py3.7.egg

Is that a copy paste error? That’s a full major version behind the current releasr of pyjwt. Make sure you have the most up to date version of PyJWT and see if you still get the error

**Comment by sraghavan-eqix** [comment] 2019-03-14 06:09
I keep getting the same error. This is when I run docker image
ImportError: cannot import name 'ExpiredSignatureError' from 'jwt' (/usr/local/lib/python3.7/site-packages/jwt-0.6.1-py3.7.egg/jwt/__init__.py)
This is my requirements.txt for the python project
I followed the suggestion in the above comment where someone has posted installing PyJWT==1.6.1 did the trick for them. But yet it fails for me. I have tried using 1.7.1 version as well

aniso8601==4.0.1
Click==7.0
Flask==1.0.2
flask-restplus==0.12.1
Flask-SQLAlchemy==2.1
gunicorn==19.9.0
itsdangerous==1.1.0
Jinja2==2.10
jsonschema==2.6.0
MarkupSafe==1.1.0
psycopg2==2.7.6.1
pytz==2018.7
six==1.11.0
SQLAlchemy==1.2.14
Werkzeug==0.14.1
PyYAML==3.13
requests==2.21.0
requests-oauthlib==1.2.0
rsa==4.0
kubernetes==8.0.1
grpcio>=1.19.0
grpcio-tools==1.19.0
protobuf==3.7.0
supermutes==0.2.5
boto3==1.0.0
botocore==1.0.0
google-auth==1.6.3
pyhelm==0.0.9
helm-charts==1.0.15
certifi>=2017.4.17
logger==1.4
Flask-JWT-Extended==3.18.0
jwt==0.6.1
PyJWT==1.6.1
Flask-JWT==0.2.0

**Comment by vimalloc** [comment] 2019-03-14 13:50
You have jwt and PyJWT installed which conflict with each other. Uninstall jwt and leave PyJWT installed and you should be good to go.

**Comment by vimalloc** [comment] 2019-03-14 13:51
You will also want to remove flask-jwt and only have flask-jwt-extended installed.

**Comment by sraghavan-eqix** [comment] 2019-03-18 22:59
Hi,
Thanks for the comments. I think that issue gets resolved but now I am getting this error. Please help


File "/home/demo/.local/lib/python3.5/site-packages/Flask_JWT_Extended-3.7.2-py3.5.egg/flask_jwt_extended/utils.py", line 80, in decode_token

    csrf_value=csrf_value

  File "/home/demo/.local/lib/python3.5/site-packages/Flask_JWT_Extended-3.7.2-py3.5.egg/flask_jwt_extended/tokens.py", line 126, in decode_jwt

    raise JWTDecodeError("Missing claim: fresh")

flask_jwt_extended.exceptions.JWTDecodeError: Missing claim: fresh

**Comment by devolt5** [comment] 2019-07-09 10:48
I'm still having this issue. Seems that flask-jwt-extended is not compatible to jwt v0.6.1

**Comment by vimalloc** [comment] 2019-07-09 15:19
@devolt5 This package does not use the `jwt` package, it uses the `pyjwt` package. If you have both installed it could create a conflict where `import jwt` is importing the wrong package and breaking this extension. Make sure you only have pyjwt installed

**Comment by devolt5** [comment] 2019-07-09 15:54
I'm quite new to python. Is it possible to use namespaces to avoid such naming conflicts? Especially when it comes to much used notations like "jwt"

**Comment by vimalloc** [comment] 2019-07-09 15:57
You will want to look into virtualenv, which lets you have a separate python instance for different projects. That would allow you to have jwt installed in other projects or globally (if some script or whatever needed it on your system), and a different python instance that is only for your flask project that only has `pyjwt` installed.

**Comment by jaydave1988** [comment] 2019-12-19 15:19
Hi Vimalloc,

I am still getting the same error. I am using python 3.6.2 in Win 10. 
I have tried with pyjwt==1.6.1 and latest pyjwt. 

beautifulsoup4==4.8.0
bs4==0.0.1
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
Click==7.0
cryptography==2.8
Flask==1.1.1
Flask-API==1.1
Flask-Autodoc==0.1.2
Flask-JWT-Extended==3.24.1
future==0.17.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.3
lxml==4.4.1
MarkupSafe==1.1.1
mysqlclient==1.3.12
numpy==1.17.2
pandas==0.22.0
passlib==1.7.1
pefile==2019.4.18
protlib==1.4
pycparser==2.19
pycryptodome==3.9.0
PyInstaller==3.5
PyJWT==1.7.1
python-dateutil==2.8.0
pytz==2019.3
pywin32-ctypes==0.2.0
requests==2.22.0
schedule==0.6.0
selenium==3.141.0
six==1.12.0
soupsieve==1.9.4
SQLAlchemy==1.3.10
urllib3==1.25.6
waitress==1.3.1
websocket-client==0.56.0
Werkzeug==0.16.0

Am I missing something here?

**Comment by vimalloc** [comment] 2019-12-19 15:22
Do you have a `jwt.py` file locally in your project somewhere? It might be trying to import a local `jwt.py` instead of from pyjwt.

**Comment by jaydave1988** [comment] 2019-12-19 15:40
Oops. I had a jwt.py file. After deleting, it is working. Thanks a lot.

**Comment by ChristopherKai** [comment] 2020-03-26 09:44
alembic==1.4.0
aniso8601==8.0.0
attrs==19.3.0
bcrypt==3.1.7
blinker==1.4
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cryptography==2.8
dnspython==1.16.0
et-xmlfile==1.0.1
Flask==1.1.1
Flask-Bcrypt==0.7.1
Flask-Cors==3.0.8
Flask-JWT-Extended==3.24.1
Flask-Migrate==2.5.2
Flask-RESTful==0.3.7
Flask-Script==2.0.6
Flask-SQLAlchemy==2.4.1
Flask-Testing==0.7.1
gunicorn==20.0.4
idna==2.8
itsdangerous==1.1.0
jdcal==1.4.1
Jinja2==2.10.3
Mako==1.1.1
MarkupSafe==1.1.1
more-itertools==8.2.0
mysql-connector-python==8.0.19
openpyxl==3.0.3
packaging==20.1
pluggy==0.13.1
protobuf==3.6.1
py==1.8.1
pycparser==2.19
PyJWT==1.6.1
pyparsing==2.4.6
pytest==5.3.5
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2019.3
requests==2.22.0
rope==0.16.0
six==1.14.0
SQLAlchemy==1.3.13
urllib3==1.25.8
wcwidth==0.1.8
Werkzeug==0.16.0



I have the same problem,and I dont have a jwt.py...

**Comment by marquitobb** [comment] 2021-02-23 00:53
I solved it having only
```
flask-jwt-extended
PyJWT==1.6.1
```

**Comment by DanieleB89** [comment] 2021-03-16 16:15
Why this is closed?

The error is still present...

**Comment by vimalloc-mavenlink** [comment] 2021-03-16 18:48
@DanieleB89 The error is caused by something misconfigured on your end, nothing with the application. Make sure you don't have anything that might override the `jwt` namespace, for example a different python package other then `PyJWT`, a local file or module called `jwt`, etc.
