### ISSUE TITLE
init jwt exception when creating app

### ISSUE THREAD

**Issue by RitianWu** [vimalloc/flask-jwt-extended#42] opened 2017-05-08 09:33 UTC
from jwt.algorithms import requires_cryptography

**Comment by vimalloc** [comment] 2017-05-08 13:58
What version of pyjwt do you have installed? I think this is caused by having an older version installed, I'll get a patch or today to keep things from breaking when using older versions (assuming I'm correct).

Thanks for the report.

**Comment by vimalloc** [comment] 2017-05-08 16:45
This should be fixed regardless of if you are using an older version of pyjwt in version 2.0.0. If you are still having issues after upgrading to that version, please let me know. 👍

**Closed by vimalloc** 2017-05-08 16:45 UTC
