### ISSUE TITLE
KeyError: 'JWT_ACCESS_COOKIE_NAME'

### ISSUE THREAD

**Issue by johaven** [vimalloc/flask-jwt-extended#277] opened 2019-09-29 16:21 UTC
Since the last versions i regulary got this error.
I don't understand why. This parameter has a default value.
I use Python 3.7 and Flask 1.1.1, the error seems to appear with 3.22.0 and 3.23.0 versions.

```python
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    verify_jwt_in_request()
  File "/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data = _decode_jwt_from_request(request_type='access')
  File "/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 288, in _decode_jwt_from_request
    encoded_token, csrf_token = get_encoded_token_function()
  File "/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 273, in <lambda>
    lambda: _decode_jwt_from_cookies(request_type))
  File "/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 211, in _decode_jwt_from_cookies
    cookie_key = config.access_cookie_name
  File "/venv/lib/python3.7/site-packages/flask_jwt_extended/config.py", line 98, in access_cookie_name
    return current_app.config['JWT_ACCESS_COOKIE_NAME']
KeyError: 'JWT_ACCESS_COOKIE_NAME'
```

**Comment by vimalloc** [comment] 2019-09-29 17:01
Huh, that's odd indeed, there should be a default value there for sure. There was some minor changes in the view decorators file between 3.22 and 3.23, but nothing that should affect the path taken when cookies are being used .Do you have a simple app I could use to reproduce this behavior? I'll see if I can duplicate it on my side as well.

**Comment by vimalloc** [comment] 2019-09-29 17:19
I haven't been able to duplicate this as of yet. Using the following code:

```python
from flask import Flask, jsonify, request
from flask_jwt_extended import (
    JWTManager, jwt_required, create_access_token, get_jwt_identity,
    set_access_cookies,
)

app = Flask(__name__)
app.config['JWT_TOKEN_LOCATION'] = ['headers', 'cookies']
app.config['JWT_COOKIE_CSRF_PROTECT'] = False
app.config['JWT_SECRET_KEY'] = 'super-secret'
jwt = JWTManager(app)


@app.route('/login', methods=['POST'])
def login():
    resp = jsonify({'login': True})
    set_access_cookies(resp, create_access_token(identity='test'))
    return resp, 200


@app.route('/test', methods=['GET'])
@jwt_required
def protected():
    username = get_jwt_identity()
    return jsonify({'hello': 'from {}'.format(username)}), 200
```

Is giving me these results:

```
$ http --session jwt_cookie_test :5000/test
HTTP/1.0 401 UNAUTHORIZED
Content-Length: 115
Content-Type: application/json
Date: Sun, 29 Sep 2019 17:16:55 GMT
Server: Werkzeug/0.15.5 Python/3.7.4

{
    "msg": "Missing JWT in headers or cookies (Missing Authorization Header; Missing cookie \"access_token_cookie\")"
}


$ http --session jwt_cookie_test POST :5000/login
HTTP/1.0 200 OK
Content-Length: 15
Content-Type: application/json
Date: Sun, 29 Sep 2019 17:17:13 GMT
Server: Werkzeug/0.15.5 Python/3.7.4
Set-Cookie: access_token_cookie=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Njk3Nzc0MzMsIm5iZiI6MTU2OTc3NzQzMywianRpIjoiODIxY2M1MTAtNjBlZC00N2QzLTk4ZGItNzllNzdjYmVhZDFhIiwiZXhwIjoxNTY5Nzc4MzMzLCJpZGVudGl0eSI6InRlc3QiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.tuvDw278
26aA3cLT_QOvCA_hVV1C-LgGjkIf2qdH6LY; HttpOnly; Path=/

{
    "login": true
}


$ http --session jwt_cookie_test :5000/test
HTTP/1.0 200 OK
Content-Length: 22
Content-Type: application/json
Date: Sun, 29 Sep 2019 17:17:20 GMT
Server: Werkzeug/0.15.5 Python/3.7.4

{
    "hello": "from test"
}


$ http :5000/test Authorization:"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Njk3Nzc0MzMsIm5iZiI6MTU2OTc3NzQzMywianRpIjoiODIxY2M1MTAtNjBlZC00N2QzLTk4ZGItNzllNzdjYmVhZDFhIiwiZXhwIjoxNTY5Nzc4MzMzLCJpZGVudGl0eSI6InRlc3QiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.tuvDw27826aA3cLT_QOvCA_hVV1C-LgGjkIf2qdH6LY"
HTTP/1.0 200 OK
Content-Length: 22
Content-Type: application/json
Date: Sun, 29 Sep 2019 17:18:01 GMT
Server: Werkzeug/0.15.5 Python/3.7.4

{
    "hello": "from test"
}
```

Even explicitly setting `app.config['JWT_ACCESS_COOKIE_NAME'] = None` isn't triggering this error for me. Any additional details you could provide about how to duplicate this issue would be a huge help in troubleshooting this further.

**Comment by johaven** [comment] 2019-09-29 17:29
Same problem with 3.2.1 (i continue to downgrade), i trying with Firefox (until now I used chromium for mac).

My settings:
```python
    JWT_TOKEN_LOCATION = ['cookies', 'headers']
    JWT_SESSION_COOKIE = False
    JWT_COOKIE_SECURE = not DEV
    JWT_COOKIE_CSRF_PROTECT = True
    JWT_CLAIMS_IN_REFRESH_TOKEN = True
    JWT_COOKIE_SAMESITE = 'Lax'
    JWT_ACCESS_CSRF_COOKIE_NAME = 'XSRF-TOKEN'
    JWT_REFRESH_CSRF_COOKIE_NAME = 'XSRF-REFRESH-TOKEN'
    JWT_ACCESS_CSRF_HEADER_NAME = 'X-XSRF-TOKEN'
    JWT_REFRESH_CSRF_HEADER_NAME = JWT_ACCESS_CSRF_HEADER_NAME
    JWT_ACCESS_TOKEN_EXPIRES = datetime.timedelta(minutes=30)
    JWT_REFRESH_TOKEN_EXPIRES = datetime.timedelta(hours=2)
    JWT_REFRESH_COOKIE_PATH = '/auth/refresh'
```

**Comment by johaven** [comment] 2019-09-29 18:27
i found the error but it seems to be related to the flask debugger. When a syntax (or other) error is raised, the subsequent queries return the error above.

**Comment by vimalloc** [comment] 2019-09-29 19:05
I still have not been able to duplicate this. I added a `print 'foo'` statement to the `/test` route above (invalid in python 3), and tried to hit the route when debug mode was enabled (started the server via `FLASK_ENV=development flask run`), and it returned a 500 error with the flask debugger page. Correcting the error and hitting the endpoint again resulted in the proper JSON being returned.

Either way, it sounds sounds like it has something to do with flask reloading in debug mode and not regenerating the `JWTManager(app)` or `jwt_manager.init_app(app)` after the reload. Does that sound right to you?

**Comment by johaven** [comment] 2019-10-01 15:07
I unfortunately can not reproduce the problem since the last days. 
I think it's related to the flask reload actually but it's not constant.

**Comment by vimalloc** [comment] 2019-10-10 04:08
As it sounds like it's the flask debugger being the problem and I can't reproduce the issue I'm going to close this issue. If you keep seeing this and can get a reproducible example for me to test against, feel free to re-open it, and I'll take a closer look at things :+1:

**Closed by vimalloc** 2019-10-10 04:08 UTC

**Comment by dodumosu** [comment] 2021-01-29 18:09
for what it's worth, i got this error several times, and then i realised that it was because i didn't have a `JWTManager` set up on my Flask instance, but i was using `verify_jwt_in_request()`.

Once I had a configured `JWTManager`, i stopped getting those errors
